In [1]:
import os
import pandas as pd
import numpy as np
# from scipy.integrate import cumulative_trapezoid
import re
import matplotlib.pyplot as plt
import numpy as np
from impedance.models.circuits import CustomCircuit
from impedance.visualization import plot_nyquist

## Base Set of Files

In [2]:
base_path = './LiPo Battery LP-503562-IS-3 EIS, Capacity, ECM Data'

# List all files matching stddischarge format
batteries = ['LiPO_1', 'LiPO_2', 'LiPO_3','LiPO_4', 'LiPO_5']
batteries_files = []
for battery in batteries:
    folder_path = os.path.join(base_path, battery, 'EIS_Charge_discharge')
    files_stddischarge = [f for f in os.listdir(folder_path) if re.match(r'0_\d+_1_stddischarge\.csv', f)]
    files_stddischarge.sort(key=lambda x: int(re.search(r'0_(\d+)_1_stddischarge\.csv', x).group(1)))
    batteries_files.append({'battery':battery, 'files':files_stddischarge})
batteries_files_df = pd.DataFrame(batteries_files)
# Sort files numerically by cycle number
batteries_files_df.sort_values(by='battery')

  battery                                              files
0  LiPO_1  [0_0_1_stddischarge.csv, 0_45_1_stddischarge.c...
1  LiPO_2  [0_0_1_stddischarge.csv, 0_20_1_stddischarge.c...
2  LiPO_3  [0_0_1_stddischarge.csv, 0_45_1_stddischarge.c...
3  LiPO_4  [0_0_1_stddischarge.csv, 0_45_1_stddischarge.c...
4  LiPO_5  [0_0_1_stddischarge.csv, 0_45_1_stddischarge.c...

## Capacity at different Cycles

In [3]:
cycle_vs_capacity = []
for battery in batteries:
    folder_path = os.path.join(base_path, battery, 'EIS_Charge_discharge')
    for files in batteries_files_df[batteries_files_df['battery'] == battery]['files']:
        for file in files:
            cycle = int(file.split('_')[1])
            df = pd.read_csv(os.path.join(folder_path, file), header=None, names=['Time', 'Voltage', 'Current'],delimiter='\t')
            df = df.apply(pd.to_numeric, errors='coerce')
            df = df.dropna()
            df = df.sort_values(by='Time')

            time = df['Time'].values  # in seconds
            current = df['Current'].values  # in A
            capacity_As = np.trapezoid(current, time)
            capacity_Ah = capacity_As / 3600
            cycle_vs_capacity.append({
                "Battery": battery,
                "Cycle": cycle,
                "Discharge_Capacity_Ah": capacity_Ah
            })
cycle_vs_capacity_df = pd.DataFrame(cycle_vs_capacity)
cycle_vs_capacity_df = cycle_vs_capacity_df.sort_values(by=['Battery','Cycle'])
cycle_vs_capacity_df

   Battery  Cycle  Discharge_Capacity_Ah
0   LiPO_1      0               3.664491
1   LiPO_1     45               3.556919
2   LiPO_1     90               3.408802
3   LiPO_1    116               3.341066
4   LiPO_1    135               3.271616
5   LiPO_1    180               2.935235
6   LiPO_1    204               2.841165
7   LiPO_2      0               3.549720
8   LiPO_2     20               3.537430
9   LiPO_2     40               3.507533
10  LiPO_2     60               3.486257
11  LiPO_2     80               3.478146
12  LiPO_2    100               3.456602
13  LiPO_2    120               3.466071
14  LiPO_2    140               3.439036
15  LiPO_2    160               3.427796
16  LiPO_2    180               3.403485
17  LiPO_2    200               3.383511
18  LiPO_2    220               3.379293
19  LiPO_2    240               3.360400
20  LiPO_2    260               3.344430
21  LiPO_2    280               3.341753
22  LiPO_2    300               3.317482
23  LiPO_2    320               3.296353
24  LiPO_3      0               3.533592
25  LiPO_3     45               3.228158
26  LiPO_3     80               3.282660
27  LiPO_3     90               3.248635
28  LiPO_3    135               3.149270
29  LiPO_3    180               3.071844
30  LiPO_3    225               2.949057
31  LiPO_3    270               2.788708
32  LiPO_3    315               2.697002
33  LiPO_3    360               2.598890
34  LiPO_3    405               2.498358
35  LiPO_3    450               2.388251
36  LiPO_4      0               3.728836
37  LiPO_4     45               3.663238
38  LiPO_4     90               3.579674
39  LiPO_4    135               3.498220
40  LiPO_4    180               3.339384
41  LiPO_4    225               3.084525
42  LiPO_4    270               2.791790
43  LiPO_4    315               2.450959
44  LiPO_5      0               3.677780
45  LiPO_5     45               3.644678
46  LiPO_5     90               3.626306
47  LiPO_5    135               3.595693
48  LiPO_5    180               3.576752
49  LiPO_5    225               3.550722
50  LiPO_5    270               3.509780
51  LiPO_5    315               3.435751
52  LiPO_5    360               3.340795
53  LiPO_5    405               3.201308
54  LiPO_5    450               2.948585
55  LiPO_5    495               2.621200
56  LiPO_5    540               2.250180

## SoH at different Cycles

In [4]:
cycle_vs_capacity_df['SoH'] = np.nan
for battery in batteries:
    battery_df = cycle_vs_capacity_df[cycle_vs_capacity_df['Battery'] == battery].sort_values(by='Cycle')
    initial_capacity = battery_df.iloc[0]['Discharge_Capacity_Ah']
    soh_values = battery_df['Discharge_Capacity_Ah'] / initial_capacity
    cycle_vs_capacity_df.loc[battery_df.index, 'SoH'] = soh_values

cycle_vs_capacity_df
# for i, row in cycle_vs_capacity_df.iterrows():
#     print(f"Cycle {int(row['Cycle']):>3}: Capacity = {-1*row['Discharge_Capacity_Ah']:.4f} Ah, SoH = {row['SoH']:.2%}")

   Battery  Cycle  Discharge_Capacity_Ah       SoH
0   LiPO_1      0               3.664491  1.000000
1   LiPO_1     45               3.556919  0.970645
2   LiPO_1     90               3.408802  0.930225
3   LiPO_1    116               3.341066  0.911741
4   LiPO_1    135               3.271616  0.892789
5   LiPO_1    180               2.935235  0.800994
6   LiPO_1    204               2.841165  0.775323
7   LiPO_2      0               3.549720  1.000000
8   LiPO_2     20               3.537430  0.996538
9   LiPO_2     40               3.507533  0.988115
10  LiPO_2     60               3.486257  0.982122
11  LiPO_2     80               3.478146  0.979837
12  LiPO_2    100               3.456602  0.973767
13  LiPO_2    120               3.466071  0.976435
14  LiPO_2    140               3.439036  0.968819
15  LiPO_2    160               3.427796  0.965652
16  LiPO_2    180               3.403485  0.958804
17  LiPO_2    200               3.383511  0.953177
18  LiPO_2    220               3.379293  0.951988
19  LiPO_2    240               3.360400  0.946666
20  LiPO_2    260               3.344430  0.942167
21  LiPO_2    280               3.341753  0.941413
22  LiPO_2    300               3.317482  0.934575
23  LiPO_2    320               3.296353  0.928623
24  LiPO_3      0               3.533592  1.000000
25  LiPO_3     45               3.228158  0.913563
26  LiPO_3     80               3.282660  0.928987
27  LiPO_3     90               3.248635  0.919358
28  LiPO_3    135               3.149270  0.891238
29  LiPO_3    180               3.071844  0.869326
30  LiPO_3    225               2.949057  0.834578
31  LiPO_3    270               2.788708  0.789199
32  LiPO_3    315               2.697002  0.763247
33  LiPO_3    360               2.598890  0.735481
34  LiPO_3    405               2.498358  0.707031
35  LiPO_3    450               2.388251  0.675871
36  LiPO_4      0               3.728836  1.000000
37  LiPO_4     45               3.663238  0.982408
38  LiPO_4     90               3.579674  0.959998
39  LiPO_4    135               3.498220  0.938153
40  LiPO_4    180               3.339384  0.895557
41  LiPO_4    225               3.084525  0.827209
42  LiPO_4    270               2.791790  0.748703
43  LiPO_4    315               2.450959  0.657299
44  LiPO_5      0               3.677780  1.000000
45  LiPO_5     45               3.644678  0.991000
46  LiPO_5     90               3.626306  0.986004
47  LiPO_5    135               3.595693  0.977680
48  LiPO_5    180               3.576752  0.972530
49  LiPO_5    225               3.550722  0.965452
50  LiPO_5    270               3.509780  0.954320
51  LiPO_5    315               3.435751  0.934192
52  LiPO_5    360               3.340795  0.908373
53  LiPO_5    405               3.201308  0.870446
54  LiPO_5    450               2.948585  0.801730
55  LiPO_5    495               2.621200  0.712713
56  LiPO_5    540               2.250180  0.611831

# SoC for all EIS Files

In [8]:
for battery in batteries:
    folder_path = os.path.join(base_path, battery, 'EIS_Charge_discharge')
    files_EIS = [f for f in os.listdir(folder_path) if re.match(r'EIS+_\d', f)]
    files_EIS.sort(key=lambda x: int(x.split('_')[1]))
    cycle_vs_SoC_vs_file = []
    for folder in files_EIS:
        folder_path_EIS = os.path.join(folder_path, folder)
        if folder.startswith('EIS_') and os.path.isdir(folder_path_EIS):
            cycle_number = int(folder.split('_')[1])
            files_EIS_folder = [f for f in os.listdir(folder_path_EIS)]
            soc_df = None
            # Get SoC from cycle_vs_capacity_df
            for f in os.listdir(folder_path_EIS):
                if f.endswith('SOC.csv'):
                    soc_file_path = os.path.join(folder_path_EIS, f)
                    soc_df = pd.read_csv(soc_file_path, header=None, names=['SoC'], delimiter='\t')
                    soc_df = soc_df.apply(pd.to_numeric, errors='coerce')
                    soc_df = soc_df.dropna()
                    soc_df['index'] = range(len(soc_df))
                    break
            for f in os.listdir(folder_path_EIS):
                if f.endswith('.csv') and not f.endswith('SOC.csv'):
                    eis_file_path = os.path.join(folder_path_EIS, f)
                    a = int(f.split('_')[0])
                    cycle_vs_SoC_vs_file.append({
                        "Battery": battery,
                        "Cycle": cycle_number,
                        "EIS_File": f,
                        "SoC": soc_df[soc_df['index'] == a]['SoC']
                    })
            # int(folder.split('_')[0])
    cycle_vs_SoC_vs_file_df = pd.DataFrame(cycle_vs_SoC_vs_file)
    cycle_vs_SoC_vs_file_df

# EIS Fitting Results

In [ ]:
circuit,initial_guess = 'R1-p(CPE2,R2-Wo3)-W1',[
    0.1,      # R1
    1e-5,     # CPE2_T
    0.9,      # CPE2_P
    200,      # R2
    1.0,      # Wd3_R
    1e-5,     # Wd3_T    # W1_R
    1e-5      # W1_T
]

# changes

circuit_model = CustomCircuit(initial_guess=initial_guess, circuit=circuit)

In [ ]:
results_data = []
fig, ax = plt.subplots(figsize=(10, 8))
files_EIS = [f for f in os.listdir(base_path) if re.match(r'EIS+_\d', f)]
files_EIS.sort(key=lambda x: int(x.split('_')[1]))
cycle_vs_SoC_vs_file = []
for folder in files_EIS:
    folder_path = os.path.join(base_path, folder)
    if folder.startswith('EIS_') and os.path.isdir(folder_path):
        cycle_num = int(folder.split('_')[1])  
        eis_file = os.path.join(folder_path, '1_EIS.csv') 

        if os.path.exists(eis_file):
            df = pd.read_csv(eis_file, header=None, names=['Freq', 'Re', 'Im'], delimiter='\t')
            freq = df['Freq'].values
            Z_re = df['Re'].values
            Z_im = df['Im'].values

            Z = Z_re + 1j * Z_im
            circuit_model.fit(freq, Z)

            fitted_parameters = circuit_model.parameters_

            nested_param_names = circuit_model.get_param_names()
            param_names = [item for sublist in nested_param_names for item in (sublist if isinstance(sublist, list) else [sublist])]

            row_data = {
                'SoC': 90,  
                'Cycle': cycle_num,
                'SoH': results_df.loc[cycle_num, 'SoH'] if cycle_num in results_df.index else None
            }
            
            # Add circuit parameters to the row data
            for name, value in zip(param_names, fitted_parameters):
                row_data[name] = value

            # Append the row data to the results list
            results_data.append(row_data)

            # Plot using impedance-style: negative imaginary axis
            label = f"Cycle {cycle_num} - SoH {row_data['SoH']:.0%}" if row_data['SoH'] is not None else f"Cycle {cycle_num}"
            row_data['SoH'] = f"{row_data['SoH']:.0%}"  # Set SoC to 90% for all entries
            ax.plot(Z_re, -Z_im, label=label, linestyle='-', linewidth=2.5, marker='o')

# Customize the plot
ax.set_xlabel('Re(Z) [Ω]', fontsize=26, fontweight='bold')
ax.set_ylabel('-Im(Z) [Ω]', fontsize=26, fontweight='bold')
ax.set_title('EIS Spectra at SoC 90% with different SoH', fontsize=26, pad=20)
ax.tick_params(axis='both', which='major', labelsize=24)
for label in ax.get_xticklabels() + ax.get_yticklabels():
    label.set_fontweight('bold')
ax.legend(fontsize=18)
for spine in ax.spines.values():
    spine.set_linewidth(2.5)
plt.tight_layout()
plt.show()

# Convert results data to a DataFrame
results_new = pd.DataFrame(results_data)

# Save the results DataFrame to an Excel file
output_file = 'LiPO_1_EIS_Fitting_Results.csv'

# Check if the file already exists
if not os.path.exists(output_file):
    # If the file doesn't exist, write the DataFrame with the header
    results_new.to_csv(output_file, index=False)
else:
    # If the file exists, append the data without writing the header
    results_new.to_csv(output_file, mode='a', index=False, header=False)

## Main Algo

In [ ]:
results_data = []

# File paths
soc = 10
filelist_path = f"/Users/sushankmishra/Desktop/MTP_Materials/EIS Fitting/LiPo Battery LP-503562-IS-3 EIS, Capacity, ECM Data/LiPO_1/EIS_Charge_discharge/soc_val/EISFiles_SoC{soc}.csv"
base_eis_path = "/Users/sushankmishra/Desktop/MTP_Materials/EIS Fitting/LiPo Battery LP-503562-IS-3 EIS, Capacity, ECM Data/LiPO_1/EIS_Charge_discharge/EIS_{x}/{y}_EIS.csv"

# Read the filelist.txt to get x and y values
filelist_df = pd.read_csv(filelist_path, header=None, names=['x', 'y'], delimiter='\t', index_col=False)
print(filelist_df)
# Initialize the plot
fig, ax = plt.subplots(figsize=(10, 8))

# Loop through each row in the filelist
for _, row in filelist_df.iterrows():
    x = row['x']
    y = row['y']

    # Construct the EIS file path
    eis_file = base_eis_path.format(x=x, y=y)

    if os.path.exists(eis_file):
        df = pd.read_csv(eis_file, header=None, names=['Freq', 'Re', 'Im'], delimiter='\t')
        freq = df['Freq'].values
        Z_re = df['Re'].values
        Z_im = df['Im'].values

        # Fit the circuit model
        Z = Z_re + 1j * Z_im
        circuit_model.fit(freq, Z)

        # Get fitted parameters
        fitted_parameters = circuit_model.parameters_

        # Extract parameter names
        nested_param_names = circuit_model.get_param_names()
        param_names = [item for sublist in nested_param_names for item in (sublist if isinstance(sublist, list) else [sublist])]
        cycle_num = int(x)  # Assuming x corresponds to the cycle number
        soh = results_df.loc[cycle_num, 'SoH'] if cycle_num in results_df.index else None
        # Create a dictionary to store the row data
        row_data = {
            'SoC': soc,  # Assuming SoC is 90% for all files
            'Cycle': cycle_num,
            'SoH': soh
            # 'SoH': round(results_df.loc[cycle_num, 'SoH'], 2) if cycle_num in results_df.index else None
        }
        
        # Add circuit parameters to the row data
        for name, value in zip(param_names, fitted_parameters):
            row_data[name] = value

        # Append the row data to the results list
        results_data.append(row_data)

        # Plot using impedance-style: negative imaginary axis
        label = f"Cycle {cycle_num} - SoH {row_data['SoH']:.0%}" if row_data['SoH'] is not None else f"Cycle {cycle_num}"
        row_data['SoH'] = f"{row_data['SoH']:.0%}"  # Set SoC to 90% for all entries
        ax.plot(Z_re, -Z_im, label=label, linestyle='-', linewidth=2.5, marker='o')

# Customize the plot
ax.set_xlabel('Re(Z) [Ω]', fontsize=26, fontweight='bold')
ax.set_ylabel('-Im(Z) [Ω]', fontsize=26, fontweight='bold')
ax.set_title(f'EIS Spectra at SoC {soc}% with different SoH', fontsize=26, pad=20)
ax.tick_params(axis='both', which='major', labelsize=24)
for label in ax.get_xticklabels() + ax.get_yticklabels():
    label.set_fontweight('bold')
ax.legend(fontsize=18)
for spine in ax.spines.values():
    spine.set_linewidth(2.5)

# Adjust layout and show the plot
plt.tight_layout()
plt.show()
# Convert results data to a DataFrame
results_new = pd.DataFrame(results_data)

# Save the results DataFrame to an Excel file
output_file = 'LiPo Battery LP-503562-IS-3 EIS, Capacity, ECM Data/LiPO_1/EIS_Charge_discharge/EIS_Fitting_Results.csv'

# Check if the file already exists
if not os.path.exists(output_file):
    # If the file doesn't exist, write the DataFrame with the header
    results_new.to_csv(output_file, index=False)
else:
    # If the file exists, append the data without writing the header
    results_new.to_csv(output_file, mode='a', index=False, header=False)

## Checking post neglect of less than 0 values of -Z_im

In [ ]:
# results_df.set_index('Cycle', inplace=True)
if results_df.index.name != 'Cycle':
    results_df.set_index('Cycle', inplace=True)
soc = list(range(10, 101, 10))
for soc in soc:
    results_data = []
    # print(f"Processing SoC: {soc}%")
    filelist_path = f"/Users/sushankmishra/Desktop/MTP_Materials/EIS Fitting/LiPo Battery LP-503562-IS-3 EIS, Capacity, ECM Data/LiPO_1/EIS_Charge_discharge/soc_val/EISFiles_SoC{soc}.csv"
    base_eis_path = "/Users/sushankmishra/Desktop/MTP_Materials/EIS Fitting/LiPo Battery LP-503562-IS-3 EIS, Capacity, ECM Data/LiPO_1/EIS_Charge_discharge/EIS_{x}/{y}_EIS.csv"

    # Read the filelist.txt to get x and y values
    filelist_df = pd.read_csv(filelist_path, header=None, names=['x', 'y'], delimiter='\t', index_col=False)
    # print(filelist_df)
    # Initialize the plot
    fig, ax = plt.subplots(figsize=(10, 8))

    # Loop through each row in the filelist
    for _, row in filelist_df.iterrows():
        x = row['x']
        y = row['y']

        # Construct the EIS file path
        eis_file = base_eis_path.format(x=x, y=y)

        if os.path.exists(eis_file):
            df = pd.read_csv(eis_file, header=None, names=['Freq', 'Re', 'Im'], delimiter='\t')
            # freq = df['Freq'].values
            # Z_re = df['Re'].values
            # Z_im = df['Im'].values
            
            freq = df['Freq'].values
            Z_re = df['Re'].values
            Z_im = df['Im'].values

            # Filter out values where Z_im < 0
            mask = Z_im >= 0
            freq = freq[~mask]
            Z_re = Z_re[~mask]
            Z_im = Z_im[~mask]

            # Fit the circuit model
            Z = Z_re + 1j * Z_im
            circuit_model.fit(freq, Z)

            # Get fitted parameters
            fitted_parameters = circuit_model.parameters_

            # Extract parameter names
            nested_param_names = circuit_model.get_param_names()
            param_names = [item for sublist in nested_param_names for item in (sublist if isinstance(sublist, list) else [sublist])]
            cycle_num = int(x)  # Assuming x corresponds to the cycle number
            soh = results_df.loc[cycle_num, 'SoH'] if cycle_num in results_df.index else None
            # Create a dictionary to store the row data
            row_data = {
                'SoC': soc,  # Assuming SoC is 90% for all files
                'Cycle': cycle_num,
                'SoH': soh
                # 'SoH': round(results_df.loc[cycle_num, 'SoH'], 2) if cycle_num in results_df.index else None
            }
            
            # Add circuit parameters to the row data
            for name, value in zip(param_names, fitted_parameters):
                row_data[name] = value

            # Append the row data to the results list
            results_data.append(row_data)

            # Plot using impedance-style: negative imaginary axis
            label = f"Cycle {cycle_num} - SoH {row_data['SoH']:.0%}" if row_data['SoH'] is not None else f"Cycle {cycle_num}"
            row_data['SoH'] = f"{row_data['SoH']:.0%}"  # Set SoC to 90% for all entries
            ax.plot(Z_re, -Z_im, label=label, linestyle='-', linewidth=2.5, marker='o')

    # Customize the plot
    ax.set_xlabel('Re(Z) [Ω]', fontsize=26, fontweight='bold')
    ax.set_ylabel('-Im(Z) [Ω]', fontsize=26, fontweight='bold')
    ax.set_title(f'EIS Spectra at SoC {soc}% with different SoH', fontsize=26, pad=20)
    ax.tick_params(axis='both', which='major', labelsize=24)
    for label in ax.get_xticklabels() + ax.get_yticklabels():
        label.set_fontweight('bold')
    ax.legend(fontsize=18)
    for spine in ax.spines.values():
        spine.set_linewidth(2.5)

    # Adjust layout and show the plot
    # plt.tight_layout()
    # plt.show()
    # Convert results data to a DataFrame
    results_new = pd.DataFrame(results_data)

    # Save the results DataFrame to an Excel file
    output_file = './EIS_Fitting_Results_new.csv'

    # Check if the file already exists
    if not os.path.exists(output_file):
        # If the file doesn't exist, write the DataFrame with the header
        results_new.to_csv(output_file, index=False)
    else:
        # If the file exists, append the data without writing the header
        results_new.to_csv(output_file, mode='a', index=False, header=False)

## Check Fitting of ECM on Data

In [ ]:
# File paths
soc = 90
cycle = 90  # <-- Set the cycle number you want to plot
filelist_path = f"/Users/sushankmishra/Desktop/MTP_Materials/EIS Fitting/LiPo Battery LP-503562-IS-3 EIS, Capacity, ECM Data/LiPO_1/EIS_Charge_discharge/soc_val/EISFiles_SoC{soc}.csv"
base_eis_path = "/Users/sushankmishra/Desktop/MTP_Materials/EIS Fitting/LiPo Battery LP-503562-IS-3 EIS, Capacity, ECM Data/LiPO_1/EIS_Charge_discharge/EIS_{x}/{y}_EIS.csv"

# Read the filelist to get x and y values
filelist_df = pd.read_csv(filelist_path, header=None, names=['x', 'y'], delimiter='\t', index_col=False)

# Define your circuit and initial guess
circuit = 'R0-p(R1-W1,CPE1)'
initial_guess = [0.1, 200, 1, 1e-5, 0.9]
circuit_model = CustomCircuit(initial_guess=initial_guess, circuit=circuit)
# Filter for the desired cycle
if cycle in filelist_df['x'].values:
    row = filelist_df[filelist_df['x'] == cycle].iloc[0]
    x = row['x']
    y = row['y']
    eis_file = base_eis_path.format(x=x, y=y)

    if os.path.exists(eis_file):
        df = pd.read_csv(eis_file, header=None, names=['Freq', 'Re', 'Im'], delimiter='\t')
        freq = df['Freq'].values
        Z_re = df['Re'].values
        Z_im = df['Im'].values

        # Fit the circuit model
        Z = Z_re + 1j * Z_im
        circuit_model.fit(freq, Z)
        Z_fit = circuit_model.predict(freq)
        print("Fitted Parameters:", circuit_model.parameters_)
        rmse = np.sqrt(np.mean(np.abs(Z - Z_fit) ** 2))
        print(f"Fitting RMSE for cycle {cycle}: {rmse:.4e} Ω")
        # Plot experimental and fitted data
        plt.figure(figsize=(7, 7))
        plt.plot(Z_re, -Z_im, 'o', label='Experimental', markersize=7)
        plt.plot(Z_fit.real, -Z_fit.imag, '-', label='Fitted', linewidth=2.5)
        plt.xlabel("Re(Z) [Ω]", fontsize=26, fontweight='bold')
        plt.ylabel("-Im(Z) [Ω]", fontsize=26, fontweight='bold')
        plt.title(f"Nyquist Plot: At SoC {soc}% for Cycle {x}", fontsize=20, fontweight='bold', pad=20)
        plt.tick_params(axis='both', which='major', labelsize=18)
        plt.legend(fontsize=18)
        plt.grid(True)
        for spine in plt.gca().spines.values():
            spine.set_linewidth(2.5)
        for label in plt.gca().get_xticklabels() + plt.gca().get_yticklabels():
            label.set_fontweight('bold')
        plt.tight_layout()
        plt.show()
    else:
        print(f"EIS file not found for cycle {cycle}")
else:
    print(f"Cycle {cycle} not found in filelist.")

## Tried & tested

In [ ]:
# Read the filelist.txt to get x and y values
filelist_df = pd.read_csv(filelist_path, header=None, names=['x', 'y'], delimiter='\t', index_col=False)
print(filelist_df)
# Initialize the plot
fig, ax = plt.subplots(figsize=(10, 8))

# Loop through each row in the filelist
for _, row in filelist_df.iterrows():
    x = row['x']
    y = row['y']

    # Construct the EIS file path
    eis_file = base_eis_path.format(x=x, y=y)

    if os.path.exists(eis_file):
        # Load the EIS data
        df = pd.read_csv(eis_file, header=None, names=['Freq', 'Re', 'Im'], delimiter='\t', index_col=False)

        # Extract data for plotting
        freq = df['Freq'].values
        Z_re = df['Re'].values
        Z_im = df['Im'].values

        # Get SoH from earlier computed values (assuming results_df and cycle_num are defined)
        cycle_num = int(x)  # Assuming x corresponds to the cycle number
        soh = results_df.loc[cycle_num, 'SoH'] if cycle_num in results_df.index else None

        # Create label for the plot
        label = f"Cycle {cycle_num} - SoH {soh:.0%}" if soh is not None else f"Cycle {cycle_num}"

        # Plot using impedance-style: negative imaginary axis
        ax.plot(Z_re, -Z_im, label=label, linestyle='-', linewidth=2.5, marker='o')

# Customize the plot
ax.set_xlabel('Re(Z) [Ω]', fontsize=26, fontweight='bold')
ax.set_ylabel('-Im(Z) [Ω]', fontsize=26, fontweight='bold')
ax.set_title('EIS Spectra at SoC 90% with different SoH', fontsize=26, pad=20)
ax.tick_params(axis='both', which='major', labelsize=24)
for label in ax.get_xticklabels() + ax.get_yticklabels():
    label.set_fontweight('bold')
ax.legend(fontsize=18)
for spine in ax.spines.values():
    spine.set_linewidth(2.5)

# Adjust layout and show the plot
plt.tight_layout()
plt.show()